steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us.gcr.io/$PROJECT_ID/cpp:latest', '.' ]
- name: 'us.gcr.io/$PROJECT_ID/cpp:latest'
  args: ['./autogen.sh']
- name: 'us.gcr.io/$PROJECT_ID/cpp:latest'
  args: ['./configure', '--disable-tests']
- name: 'us.gcr.io/$PROJECT_ID/cpp:latest'
  args: ['make']

images: [us.gcr.io/$PROJECT_ID/cpp:latest]
